services:
  postgres:
    image: postgres:16
    container_name: bookstore-postgres
    hostname: postgres
    networks:
      - bookstore-network
    environment:
      POSTGRES_PASSWORD: bookstore_password
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: bookstore_user
    ports:
      - "5433:5432"
    volumes:
      - ./scripts/init_database.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./scripts/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookstore_user -d bookstore_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-api
    networks:
      - bookstore-network
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://bookstore_user:bookstore_password@postgres:5432/bookstore_db"
      DB_CONNECTION_STRING: "dbname=bookstore_db user=bookstore_user password=bookstore_password host=postgres port=5432"
      JWT_SECRET: "CHANGE_ME_IN_PRODUCTION_real_jwt_secret_key_2024"
      PORT: "4000"
    restart: unless-stopped

networks:
  bookstore-network:
    driver: bridge